Vagrant.configure("2") do |config|

    config.vm.define "terraform" do |tr|
      tr.vm.box = "ubuntu/jammy64"
      tr.vm.network "private_network", ip: "192.168.56.152"
      tr.vm.provider "virtualbox" do |vb|
        vb.memory = "4098"
        vb.cpus = "2"
      end
    end

end