version: '3.8'

services:
  db:
    image: postgres:15
    environment:
      POSTGRES_DB: tododb
      POSTGRES_USER: todo_user
      POSTGRES_PASSWORD: todo_pass
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck: # <--- ADD THIS SECTION
      test: ["CMD-SHELL", "pg_isready -U todo_user -d tododb"]
      interval: 5s
      timeout: 5s
      retries: 5

  api:
    build:
      context: ./backend
    depends_on:
      db:
        condition: service_healthy # <--- CHANGE THIS IN depends_on
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ConnectionStrings__DefaultConnection: Host=db;Port=5432;Database=tododb;Username=todo_user;Password=todo_pass
    ports:
      - "5001:80"

  frontend:
    image: nginx:alpine
    volumes:
      - ./frontend:/usr/share/nginx/html:ro
    ports:
      - "8080:80"
    depends_on:
      - api

volumes:
  postgres-data: