Vagrant.configure("2") do |config|
    config.vm.provision "shell", inline: "echo Hello"
  
    config.vm.define "db" do |db|
      db.vm.box = "ubuntu/jammy64"
      db.vm.network "private_network", ip: "192.168.18.108"
      db.vm.provider "virtualbox" do |vb|
        vb.memory = "1024"
        vb.cpus = "1"
      end
      db.vm.provision "shell", inline: <<-SHELL
        sudo apt update
        sudo apt install mysql-server -y
        sudo hostnamectl set-hostname dbserver
        mysql -u root -e 'CREATE DATABASE wordpress;'
        mysql -u root -e 'CREATE USER wordpress@localhost IDENTIFIED BY "admin123";'
        mysql -u root -e 'GRANT SELECT, INSERT, UPDATE, DELETE, CREATE, DROP, ALTER ON wordpress.* TO 'wordpress'@'192.168.1.100' TO 'wordpress'@'192.168.18.109' WITH GRANT OPTION;'
        mysql -u root -e 'FLUSH PRIVILEGES;'

        sudo -u mysql sed -i 's/127.0.0.1/192.168.18.109/g' /etc/mysql/mysql.conf.d/mysqld.cnf
        sudo service mysql start
      SHELL
    end

    config.vm.define "web" do |web|
      web.vm.box = "ubuntu/jammy64"
      web.vm.network "private_network", ip: "192.168.18.109"
      web.vm.synced_folder "./vagrant", "/vagrant"
      web.vm.provider "virtualbox" do |vb|
        vb.memory = "1024"
        vb.cpus = 2
      end
      web.vm.provision "shell", inline: <<-SHELL
        sudo apt update
        sudo hostnamectl set-hostname webserver
        sudo apt install apache2 \
                    ghostscript \
                    libapache2-mod-php \
                    php \
                    php-bcmath \
                    php-curl \
                    php-imagick \
                    php-intl \
                    php-json \
                    php-mbstring \
                    php-mysql \
                    php-xml \
                    php-zip -y
    
        sudo mkdir -p /srv/www
        sudo chown www-data: /srv/www
        curl https://wordpress.org/latest.tar.gz | sudo -u www-data tar zx -C /srv/www
        cp /vagrant/wordpress.conf /etc/apache2/sites-available/wordpress.conf
        
        sudo a2ensite wordpress
        sudo a2enmod rewrite
        sudo a2dissite 000-default
        sudo service apache2 reload

        sudo -u www-data cp /srv/www/wordpress/wp-config-sample.php /srv/www/wordpress/wp-config.php
        sudo -u www-data sed -i 's/localhost/192.168.18.108/' /srv/www/wordpress/wp-config.php
        sudo -u www-data sed -i 's/database_name_here/wordpress/' /srv/www/wordpress/wp-config.php
        sudo -u www-data sed -i 's/username_here/wordpress/' /srv/www/wordpress/wp-config.php
        sudo -u www-data sed -i 's/password_here/admin123/' /srv/www/wordpress/wp-config.php
      SHELL
    end
end